### ISSUE TITLE
Authentication and Authorization

### ISSUE THREAD

**Issue by matinayo** [matinayo/generic-ecommerce-API#3]
JWT
- [x] #12
- [x] role based authorization with JWT #15 
- [x] read JWT authorization claims of a user from JWT #15 
- [x] refresh tokens #15 
- [x] role management #15 
- [x] endpoint access and authorization #15
